{
  enable = true;
  brews = [
		"ansible"
		"ansible-lint"
		"autoconf"
    "awscli"
    "awsebcli"
		"bazelisk"
    "cmake"
    "coreutils"
		"dotnet"
    "ffmpeg"
    "fzf"
    "gnupg"
    "golang"
    "hashicorp/tap/packer"
    "helm"
    "htop"
		"huggingface-cli"
    "jq"
    "kubectl"
    "kubectx"
    "libffi"
    "libheif"
    "librsvg"
    "libsoup"
		"libmagic"
    "meson"
		"m4"
    "minikube"
    "nmap"
    "opencv"
    "picocom"
    "pinentry-mac"
    "pkg-config"
		"portaudio"
    "pyenv"
    "pytorch"
    "rustup"
		"stripe/stripe-cli/stripe"
    "talloc"
    "tensorflow"
    "terraform"
		"terraform-docs"
    "terragrunt"
    "tmux"
    "trash"
    "volta"
    "yt-dlp"
  ];
  casks = [
    "alfred"
    "amethyst"
    "appcleaner"
    "backblaze"
    "balenaetcher"
    "beekeeper-studio"
    "blender"
    "copyq"
    "discord"
    "disk-drill"
    "docker"
    "figma"
    "firefox"
    "google-chrome"
    "iterm2"
    "keepassxc"
    "lens"
    "logseq"
    "mullvadvpn"
		"mysqlworkbench"
    "obsidian"
		"postman"
    "resilio-sync"
    # "runjs"
    "signal"
    "slack"
		"spectacle"
    "spotify"
    "telegram"
    "transmission"
    # "tunnelblick"
		"vagrant"
    "visual-studio-code"
    "vlc"
    "whatsapp"
    "wireshark"
    "zoom"
  ];
  taps = [
    "hashicorp/tap"
    "stripe/stripe-cli"
  ];
  onActivation = {
    autoUpdate = true;
    upgrade = true;
    cleanup = "uninstall";
  };
}
